<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.UMKKWBa' shared service.

return $this->privates['.service_locator.UMKKWBa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'token' => ['privates', '.errored..service_locator.UMKKWBa.App\\Entity\\Token', NULL, 'Cannot autowire service ".service_locator.UMKKWBa": it references class "App\\Entity\\Token" but no such service exists.'],
]);
