<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.KL.7_it' shared service.

return $this->privates['.service_locator.KL.7_it'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'video' => ['privates', '.errored..service_locator.KL.7_it.App\\Entity\\Video', NULL, 'Cannot autowire service ".service_locator.KL.7_it": it references class "App\\Entity\\Video" but no such service exists.'],
]);
