<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AccountController::addPictureUser' => ['privates', '.service_locator.FufKbwa', 'get_ServiceLocator_FufKbwaService.php', true],
    'App\\Controller\\AccountController::deleteAccount' => ['privates', '.service_locator.FufKbwa', 'get_ServiceLocator_FufKbwaService.php', true],
    'App\\Controller\\AccountController::editPictureUser' => ['privates', '.service_locator.FufKbwa', 'get_ServiceLocator_FufKbwaService.php', true],
    'App\\Controller\\AccountController::forGotPassword' => ['privates', '.service_locator.pT7OkR4', 'get_ServiceLocator_PT7OkR4Service.php', true],
    'App\\Controller\\AccountController::restPassword' => ['privates', '.service_locator.UMKKWBa', 'get_ServiceLocator_UMKKWBaService.php', true],
    'App\\Controller\\AccountController::updatePassword' => ['privates', '.service_locator.TDdPPKD', 'get_ServiceLocator_TDdPPKDService.php', true],
    'App\\Controller\\CommentController::deleteComment' => ['privates', '.service_locator.9dB2Vp3', 'get_ServiceLocator_9dB2Vp3Service.php', true],
    'App\\Controller\\HomeController::index' => ['privates', '.service_locator.FUxIn3u', 'get_ServiceLocator_FUxIn3uService.php', true],
    'App\\Controller\\HomeController::loadMore' => ['privates', '.service_locator.FUxIn3u', 'get_ServiceLocator_FUxIn3uService.php', true],
    'App\\Controller\\HomeController::show' => ['privates', '.service_locator.QmdUPPW', 'get_ServiceLocator_QmdUPPWService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.75cXSiM', 'get_ServiceLocator_75cXSiMService.php', true],
    'App\\Controller\\SecurityController::validateToken' => ['privates', '.service_locator.Q_HsDri', 'get_ServiceLocator_QHsDriService.php', true],
    'App\\Controller\\TrickController::add' => ['privates', '.service_locator.FufKbwa', 'get_ServiceLocator_FufKbwaService.php', true],
    'App\\Controller\\TrickController::addPicture' => ['privates', '.service_locator.g0xsJI.', 'get_ServiceLocator_G0xsJI_Service.php', true],
    'App\\Controller\\TrickController::addVideo' => ['privates', '.service_locator.nYuTfgG', 'get_ServiceLocator_NYuTfgGService.php', true],
    'App\\Controller\\TrickController::deletePicture' => ['privates', '.service_locator.RwlGFZ_', 'get_ServiceLocator_RwlGFZService.php', true],
    'App\\Controller\\TrickController::deleteTrick' => ['privates', '.service_locator.7as.sRK', 'get_ServiceLocator_7as_SRKService.php', true],
    'App\\Controller\\TrickController::deleteVideo' => ['privates', '.service_locator.KL.7_it', 'get_ServiceLocator_KL_7ItService.php', true],
    'App\\Controller\\TrickController::edit' => ['privates', '.service_locator.7as.sRK', 'get_ServiceLocator_7as_SRKService.php', true],
    'App\\Controller\\AccountController:addPictureUser' => ['privates', '.service_locator.FufKbwa', 'get_ServiceLocator_FufKbwaService.php', true],
    'App\\Controller\\AccountController:deleteAccount' => ['privates', '.service_locator.FufKbwa', 'get_ServiceLocator_FufKbwaService.php', true],
    'App\\Controller\\AccountController:editPictureUser' => ['privates', '.service_locator.FufKbwa', 'get_ServiceLocator_FufKbwaService.php', true],
    'App\\Controller\\AccountController:forGotPassword' => ['privates', '.service_locator.pT7OkR4', 'get_ServiceLocator_PT7OkR4Service.php', true],
    'App\\Controller\\AccountController:restPassword' => ['privates', '.service_locator.UMKKWBa', 'get_ServiceLocator_UMKKWBaService.php', true],
    'App\\Controller\\AccountController:updatePassword' => ['privates', '.service_locator.TDdPPKD', 'get_ServiceLocator_TDdPPKDService.php', true],
    'App\\Controller\\CommentController:deleteComment' => ['privates', '.service_locator.9dB2Vp3', 'get_ServiceLocator_9dB2Vp3Service.php', true],
    'App\\Controller\\HomeController:index' => ['privates', '.service_locator.FUxIn3u', 'get_ServiceLocator_FUxIn3uService.php', true],
    'App\\Controller\\HomeController:loadMore' => ['privates', '.service_locator.FUxIn3u', 'get_ServiceLocator_FUxIn3uService.php', true],
    'App\\Controller\\HomeController:show' => ['privates', '.service_locator.QmdUPPW', 'get_ServiceLocator_QmdUPPWService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.75cXSiM', 'get_ServiceLocator_75cXSiMService.php', true],
    'App\\Controller\\SecurityController:validateToken' => ['privates', '.service_locator.Q_HsDri', 'get_ServiceLocator_QHsDriService.php', true],
    'App\\Controller\\TrickController:add' => ['privates', '.service_locator.FufKbwa', 'get_ServiceLocator_FufKbwaService.php', true],
    'App\\Controller\\TrickController:addPicture' => ['privates', '.service_locator.g0xsJI.', 'get_ServiceLocator_G0xsJI_Service.php', true],
    'App\\Controller\\TrickController:addVideo' => ['privates', '.service_locator.nYuTfgG', 'get_ServiceLocator_NYuTfgGService.php', true],
    'App\\Controller\\TrickController:deletePicture' => ['privates', '.service_locator.RwlGFZ_', 'get_ServiceLocator_RwlGFZService.php', true],
    'App\\Controller\\TrickController:deleteTrick' => ['privates', '.service_locator.7as.sRK', 'get_ServiceLocator_7as_SRKService.php', true],
    'App\\Controller\\TrickController:deleteVideo' => ['privates', '.service_locator.KL.7_it', 'get_ServiceLocator_KL_7ItService.php', true],
    'App\\Controller\\TrickController:edit' => ['privates', '.service_locator.7as.sRK', 'get_ServiceLocator_7as_SRKService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
