<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.I5wwOyx' shared service.

return $this->privates['.service_locator.I5wwOyx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'commentRepo' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService.php', true],
    'trick' => ['privates', '.errored..service_locator.I5wwOyx.App\\Entity\\Trick', NULL, 'Cannot autowire service ".service_locator.I5wwOyx": it references class "App\\Entity\\Trick" but no such service exists.'],
]);
