<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.FUxIn3u' shared service.

return $this->privates['.service_locator.FUxIn3u'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'trickRepo' => ['privates', 'App\\Repository\\TrickRepository', 'getTrickRepositoryService.php', true],
]);
