<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\TokenSendler' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/TokenSendler.php';

return $this->privates['App\Service\TokenSendler'] = new \App\Service\TokenSendler(($this->services['swiftmailer.mailer.default'] ?? $this->load('getSwiftmailer_Mailer_DefaultService.php')), ($this->services['twig'] ?? $this->getTwigService()));
